---
version: '3'

env:
  CGO_ENABLED: 0

tasks:
  test:
    summary: Run tests
    cmds:
      - task: test-deps-up
      - task: test-run
      - task: test-deps-down

  test-deps-up:
    summary: Starts test dependencies
    cmds:
      - cmd: docker compose up --detach --wait

  test-deps-down:
    summary: Stops test dependencies
    cmds:
      - cmd: docker compose down -v

  test-run:
    summary: Runs tests, must have dependencies running in the docker compose
    cmds:
      - cmd: go test -timeout 2m -cover -coverprofile=coverage.txt -covermode=atomic ./...
    vars:
      PG_PORT:
        # `docker compose port postgres 5432` -> "0.0.0.0:52041"
        sh: docker compose port postgres 5432 | cut -f2 -d":"
    env:
      PGHOST: localhost
      PGPORT: "{{.PG_PORT}}"
      PGUSER: test
      PGPASSWORD: test
      PGSSLMODE: disable
